### ISSUE TITLE
Problem when installing on R 4.0

### ISSUE THREAD

**Issue by geraldocantelli** [rsilvabioinfo/ProbMetab#5]
Hello,
I need to install the package ProbMetab on R 4.0 but I found the next error:
Skipping 3 packages not available: multtest, RCytoscape, graph
The packages multtest and graph are already installed (by Bioconductor::install) and the Rcytoscape seems was updated to another package name version and the one that was called Rcytoscape doesn't allow installation on R 4.0.

Can some one help me please?
Best regards,
Geraldo Cesar Cantelli
Bioinformatic specialist

**Comment by rsilvabioinfo** [comment]
Hello Geraldo,

The instructions here may help
http://labpib.fmrp.usp.br/methods/probmetab/

One option would be to downgrade your R version. If you don't want to go
this route, you can download the package on the link above, then, remove
Rcytoscape from 'Depends' section and try to install
https://github.com/rsilvabioinfo/ProbMetab/blob/master/DESCRIPTION

Rcytoscape is only used at the end of the workflow.

I have to warn you, ProbMetab is no being maintained, I recommend you to
use something more updated, such as IPA
https://pubs.acs.org/doi/abs/10.1021/acs.analchem.9b02354

Which has the same concept, or
https://www.metaboanalyst.ca
https://github.com/xia-lab/MetaboAnalystR

which implements 'Mummichog' with a very similar concept.

Cheers,
Ricardo


Em ter., 2 de fev. de 2021 às 13:58, geraldocantelli <
notifications@github.com> escreveu:

**Comment by geraldocantelli** [comment]
Thank you very much Ricardo.
